/**
 * geins-management-api-sdk-js
 *  Geins Management API is an RESTful api to power your applications who manages your geins services. Geins provides an easy-to-use and scalable solution for managing all aspects of an online store, from product listings and customer information to order processing and payment transactions.   :::tip With this API, you can build custom applications and integrate with third-party systems, dashboards and other bussiness logic apps. :::    ## Getting started Once you have created an account, you can start using the Management API by creating an `API key`. You can create as many API keys as you need. Each `API key` is connected to a specific account so you can keep track of operations and manage keys. You can find your `API key` in the `geins merchant center`.   ### Fast track Use one of our [SDKs](https://docs.geins.io/docs/sdk/introduction) to get started quickly. The SDKs are available for the most popular programming languages and frameworks.  Or, if you prefer to just take it for a test run:  [![Run in Postman](https://run.pstmn.io/button.svg)](https://god.gw.postman.com/run-collection/25895885-aaf6598f-1a7c-4949-85d7-ba846c42d553?action=collection%2Ffork&collection-url=entityId%3D25895885-aaf6598f-1a7c-4949-85d7-ba846c42d553%26entityType%3Dcollection%26workspaceId%3Da2a179ce-158e-46b0-8d06-e9640f45112c)  ### Authentication Two authentication methods are supported:   - `API Key`   - `Basic Auth` 
 *
 * The version of the OpenAPI document: v1.7.1
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 *
 */

import ApiClient from '../ApiClient';

/**
 * The OrderProcessedRefund model module.
 * @module model/OrderProcessedRefund
 * @version v1.7.1
 */
class OrderProcessedRefund {
    /**
     * Constructs a new <code>OrderProcessedRefund</code>.
     * @alias module:model/OrderProcessedRefund
     */
    constructor() { 
        
        OrderProcessedRefund.initialize(this);
    }

    /**
     * Initializes the fields of this object.
     * This method is used by the constructors of any subclasses, in order to implement multiple inheritance (mix-ins).
     * Only for internal use.
     */
    static initialize(obj) { 
    }

    /**
     * Constructs a <code>OrderProcessedRefund</code> from a plain JavaScript object, optionally creating a new instance.
     * Copies all relevant properties from <code>data</code> to <code>obj</code> if supplied or a new instance if not.
     * @param {Object} data The plain JavaScript object bearing properties of interest.
     * @param {module:model/OrderProcessedRefund} obj Optional instance to populate.
     * @return {module:model/OrderProcessedRefund} The populated <code>OrderProcessedRefund</code> instance.
     */
    static constructFromObject(data, obj) {
        if (data) {
            obj = obj || new OrderProcessedRefund();

            if (data.hasOwnProperty('RefundId')) {
                obj['RefundId'] = ApiClient.convertToType(data['RefundId'], 'String');
            }
            if (data.hasOwnProperty('ExternalId')) {
                obj['ExternalId'] = ApiClient.convertToType(data['ExternalId'], 'String');
            }
            if (data.hasOwnProperty('Reference')) {
                obj['Reference'] = ApiClient.convertToType(data['Reference'], 'String');
            }
            if (data.hasOwnProperty('ProcessedOn')) {
                obj['ProcessedOn'] = ApiClient.convertToType(data['ProcessedOn'], 'Date');
            }
        }
        return obj;
    }

    /**
     * Validates the JSON data with respect to <code>OrderProcessedRefund</code>.
     * @param {Object} data The plain JavaScript object bearing properties of interest.
     * @return {boolean} to indicate whether the JSON data is valid with respect to <code>OrderProcessedRefund</code>.
     */
    static validateJSON(data) {
        // ensure the json data is a string
        if (data['RefundId'] && !(typeof data['RefundId'] === 'string' || data['RefundId'] instanceof String)) {
            throw new Error("Expected the field `RefundId` to be a primitive type in the JSON string but got " + data['RefundId']);
        }
        // ensure the json data is a string
        if (data['ExternalId'] && !(typeof data['ExternalId'] === 'string' || data['ExternalId'] instanceof String)) {
            throw new Error("Expected the field `ExternalId` to be a primitive type in the JSON string but got " + data['ExternalId']);
        }
        // ensure the json data is a string
        if (data['Reference'] && !(typeof data['Reference'] === 'string' || data['Reference'] instanceof String)) {
            throw new Error("Expected the field `Reference` to be a primitive type in the JSON string but got " + data['Reference']);
        }

        return true;
    }


}



/**
 * @member {String} RefundId
 */
OrderProcessedRefund.prototype['RefundId'] = undefined;

/**
 * @member {String} ExternalId
 */
OrderProcessedRefund.prototype['ExternalId'] = undefined;

/**
 * @member {String} Reference
 */
OrderProcessedRefund.prototype['Reference'] = undefined;

/**
 * @member {Date} ProcessedOn
 */
OrderProcessedRefund.prototype['ProcessedOn'] = undefined;






export default OrderProcessedRefund;

