/**
 * geins-management-api-sdk-js
 *  Geins Management API is an RESTful api to power your applications who manages your geins services. Geins provides an easy-to-use and scalable solution for managing all aspects of an online store, from product listings and customer information to order processing and payment transactions.   :::tip With this API, you can build custom applications and integrate with third-party systems, dashboards and other bussiness logic apps. :::    ## Getting started Once you have created an account, you can start using the Management API by creating an `API key`. You can create as many API keys as you need. Each `API key` is connected to a specific account so you can keep track of operations and manage keys. You can find your `API key` in the `geins merchant center`.   ### Fast track Use one of our [SDKs](https://docs.geins.io/docs/sdk/introduction) to get started quickly. The SDKs are available for the most popular programming languages and frameworks.  Or, if you prefer to just take it for a test run:  [![Run in Postman](https://run.pstmn.io/button.svg)](https://god.gw.postman.com/run-collection/25895885-aaf6598f-1a7c-4949-85d7-ba846c42d553?action=collection%2Ffork&collection-url=entityId%3D25895885-aaf6598f-1a7c-4949-85d7-ba846c42d553%26entityType%3Dcollection%26workspaceId%3Da2a179ce-158e-46b0-8d06-e9640f45112c)  ### Authentication Two authentication methods are supported:   - `API Key`   - `Basic Auth` 
 *
 * The version of the OpenAPI document: v1.7.1
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 *
 */

import ApiClient from '../ApiClient';
import PageAreaModelsReadPageWidget from './PageAreaModelsReadPageWidget';

/**
 * The PageAreaModelsReadPageWidgetContainer model module.
 * @module model/PageAreaModelsReadPageWidgetContainer
 * @version v1.7.1
 */
class PageAreaModelsReadPageWidgetContainer {
    /**
     * Constructs a new <code>PageAreaModelsReadPageWidgetContainer</code>.
     * This class represents a collection of widgets, and defines how they should be layouted in the area they are rendered in.
     * @alias module:model/PageAreaModelsReadPageWidgetContainer
     */
    constructor() { 
        
        PageAreaModelsReadPageWidgetContainer.initialize(this);
    }

    /**
     * Initializes the fields of this object.
     * This method is used by the constructors of any subclasses, in order to implement multiple inheritance (mix-ins).
     * Only for internal use.
     */
    static initialize(obj) { 
    }

    /**
     * Constructs a <code>PageAreaModelsReadPageWidgetContainer</code> from a plain JavaScript object, optionally creating a new instance.
     * Copies all relevant properties from <code>data</code> to <code>obj</code> if supplied or a new instance if not.
     * @param {Object} data The plain JavaScript object bearing properties of interest.
     * @param {module:model/PageAreaModelsReadPageWidgetContainer} obj Optional instance to populate.
     * @return {module:model/PageAreaModelsReadPageWidgetContainer} The populated <code>PageAreaModelsReadPageWidgetContainer</code> instance.
     */
    static constructFromObject(data, obj) {
        if (data) {
            obj = obj || new PageAreaModelsReadPageWidgetContainer();

            if (data.hasOwnProperty('Id')) {
                obj['Id'] = ApiClient.convertToType(data['Id'], 'Number');
            }
            if (data.hasOwnProperty('Name')) {
                obj['Name'] = ApiClient.convertToType(data['Name'], 'String');
            }
            if (data.hasOwnProperty('ClassNames')) {
                obj['ClassNames'] = ApiClient.convertToType(data['ClassNames'], ['String']);
            }
            if (data.hasOwnProperty('Active')) {
                obj['Active'] = ApiClient.convertToType(data['Active'], 'Boolean');
            }
            if (data.hasOwnProperty('Layout')) {
                obj['Layout'] = ApiClient.convertToType(data['Layout'], 'String');
            }
            if (data.hasOwnProperty('ResponsiveMode')) {
                obj['ResponsiveMode'] = ApiClient.convertToType(data['ResponsiveMode'], 'String');
            }
            if (data.hasOwnProperty('Visibility')) {
                obj['Visibility'] = ApiClient.convertToType(data['Visibility'], 'String');
            }
            if (data.hasOwnProperty('Design')) {
                obj['Design'] = ApiClient.convertToType(data['Design'], 'String');
            }
            if (data.hasOwnProperty('Widgets')) {
                obj['Widgets'] = ApiClient.convertToType(data['Widgets'], [PageAreaModelsReadPageWidget]);
            }
        }
        return obj;
    }

    /**
     * Validates the JSON data with respect to <code>PageAreaModelsReadPageWidgetContainer</code>.
     * @param {Object} data The plain JavaScript object bearing properties of interest.
     * @return {boolean} to indicate whether the JSON data is valid with respect to <code>PageAreaModelsReadPageWidgetContainer</code>.
     */
    static validateJSON(data) {
        // ensure the json data is a string
        if (data['Name'] && !(typeof data['Name'] === 'string' || data['Name'] instanceof String)) {
            throw new Error("Expected the field `Name` to be a primitive type in the JSON string but got " + data['Name']);
        }
        // ensure the json data is an array
        if (!Array.isArray(data['ClassNames'])) {
            throw new Error("Expected the field `ClassNames` to be an array in the JSON data but got " + data['ClassNames']);
        }
        // ensure the json data is a string
        if (data['Layout'] && !(typeof data['Layout'] === 'string' || data['Layout'] instanceof String)) {
            throw new Error("Expected the field `Layout` to be a primitive type in the JSON string but got " + data['Layout']);
        }
        // ensure the json data is a string
        if (data['ResponsiveMode'] && !(typeof data['ResponsiveMode'] === 'string' || data['ResponsiveMode'] instanceof String)) {
            throw new Error("Expected the field `ResponsiveMode` to be a primitive type in the JSON string but got " + data['ResponsiveMode']);
        }
        // ensure the json data is a string
        if (data['Visibility'] && !(typeof data['Visibility'] === 'string' || data['Visibility'] instanceof String)) {
            throw new Error("Expected the field `Visibility` to be a primitive type in the JSON string but got " + data['Visibility']);
        }
        // ensure the json data is a string
        if (data['Design'] && !(typeof data['Design'] === 'string' || data['Design'] instanceof String)) {
            throw new Error("Expected the field `Design` to be a primitive type in the JSON string but got " + data['Design']);
        }
        if (data['Widgets']) { // data not null
            // ensure the json data is an array
            if (!Array.isArray(data['Widgets'])) {
                throw new Error("Expected the field `Widgets` to be an array in the JSON data but got " + data['Widgets']);
            }
            // validate the optional field `Widgets` (array)
            for (const item of data['Widgets']) {
                PageAreaModelsReadPageWidget.validateJsonObject(item);
            };
        }

        return true;
    }


}



/**
 * The primary ID of this container
 * @member {Number} Id
 */
PageAreaModelsReadPageWidgetContainer.prototype['Id'] = undefined;

/**
 * The descriptive user defined name of this container, which is used to distinguish this container in a container library
 * @member {String} Name
 */
PageAreaModelsReadPageWidgetContainer.prototype['Name'] = undefined;

/**
 * The CSS class names this container should use.
 * @member {Array.<String>} ClassNames
 */
PageAreaModelsReadPageWidgetContainer.prototype['ClassNames'] = undefined;

/**
 * @member {Boolean} Active
 */
PageAreaModelsReadPageWidgetContainer.prototype['Active'] = undefined;

/**
 * @member {String} Layout
 */
PageAreaModelsReadPageWidgetContainer.prototype['Layout'] = undefined;

/**
 * @member {String} ResponsiveMode
 */
PageAreaModelsReadPageWidgetContainer.prototype['ResponsiveMode'] = undefined;

/**
 * @member {String} Visibility
 */
PageAreaModelsReadPageWidgetContainer.prototype['Visibility'] = undefined;

/**
 * @member {String} Design
 */
PageAreaModelsReadPageWidgetContainer.prototype['Design'] = undefined;

/**
 * The configured widgets held by this container
 * @member {Array.<module:model/PageAreaModelsReadPageWidget>} Widgets
 */
PageAreaModelsReadPageWidgetContainer.prototype['Widgets'] = undefined;






export default PageAreaModelsReadPageWidgetContainer;

