/**
 * geins-management-api-sdk-js
 *  Geins Management API is an RESTful api to power your applications who manages your geins services. Geins provides an easy-to-use and scalable solution for managing all aspects of an online store, from product listings and customer information to order processing and payment transactions.   :::tip With this API, you can build custom applications and integrate with third-party systems, dashboards and other bussiness logic apps. :::    ## Getting started Once you have created an account, you can start using the Management API by creating an `API key`. You can create as many API keys as you need. Each `API key` is connected to a specific account so you can keep track of operations and manage keys. You can find your `API key` in the `geins merchant center`.   ### Fast track Use one of our [SDKs](https://docs.geins.io/docs/sdk/introduction) to get started quickly. The SDKs are available for the most popular programming languages and frameworks.  Or, if you prefer to just take it for a test run:  [![Run in Postman](https://run.pstmn.io/button.svg)](https://god.gw.postman.com/run-collection/25895885-aaf6598f-1a7c-4949-85d7-ba846c42d553?action=collection%2Ffork&collection-url=entityId%3D25895885-aaf6598f-1a7c-4949-85d7-ba846c42d553%26entityType%3Dcollection%26workspaceId%3Da2a179ce-158e-46b0-8d06-e9640f45112c)  ### Authentication Two authentication methods are supported:   - `API Key`   - `Basic Auth` 
 *
 * The version of the OpenAPI document: v1.7.1
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 *
 */

import ApiClient from '../ApiClient';
import ProductModelsWriteProduct from './ProductModelsWriteProduct';

/**
 * The VariantModelsWriteVariantGroup model module.
 * @module model/VariantModelsWriteVariantGroup
 * @version v1.7.1
 */
class VariantModelsWriteVariantGroup {
    /**
     * Constructs a new <code>VariantModelsWriteVariantGroup</code>.
     * A variant group for a collection of related variants.
     * @alias module:model/VariantModelsWriteVariantGroup
     */
    constructor() { 
        
        VariantModelsWriteVariantGroup.initialize(this);
    }

    /**
     * Initializes the fields of this object.
     * This method is used by the constructors of any subclasses, in order to implement multiple inheritance (mix-ins).
     * Only for internal use.
     */
    static initialize(obj) { 
    }

    /**
     * Constructs a <code>VariantModelsWriteVariantGroup</code> from a plain JavaScript object, optionally creating a new instance.
     * Copies all relevant properties from <code>data</code> to <code>obj</code> if supplied or a new instance if not.
     * @param {Object} data The plain JavaScript object bearing properties of interest.
     * @param {module:model/VariantModelsWriteVariantGroup} obj Optional instance to populate.
     * @return {module:model/VariantModelsWriteVariantGroup} The populated <code>VariantModelsWriteVariantGroup</code> instance.
     */
    static constructFromObject(data, obj) {
        if (data) {
            obj = obj || new VariantModelsWriteVariantGroup();

            if (data.hasOwnProperty('Name')) {
                obj['Name'] = ApiClient.convertToType(data['Name'], 'String');
            }
            if (data.hasOwnProperty('CollapseInLists')) {
                obj['CollapseInLists'] = ApiClient.convertToType(data['CollapseInLists'], 'Boolean');
            }
            if (data.hasOwnProperty('VariantLabels')) {
                obj['VariantLabels'] = ApiClient.convertToType(data['VariantLabels'], ['String']);
            }
            if (data.hasOwnProperty('Products')) {
                obj['Products'] = ApiClient.convertToType(data['Products'], [ProductModelsWriteProduct]);
            }
        }
        return obj;
    }

    /**
     * Validates the JSON data with respect to <code>VariantModelsWriteVariantGroup</code>.
     * @param {Object} data The plain JavaScript object bearing properties of interest.
     * @return {boolean} to indicate whether the JSON data is valid with respect to <code>VariantModelsWriteVariantGroup</code>.
     */
    static validateJSON(data) {
        // ensure the json data is a string
        if (data['Name'] && !(typeof data['Name'] === 'string' || data['Name'] instanceof String)) {
            throw new Error("Expected the field `Name` to be a primitive type in the JSON string but got " + data['Name']);
        }
        // ensure the json data is an array
        if (!Array.isArray(data['VariantLabels'])) {
            throw new Error("Expected the field `VariantLabels` to be an array in the JSON data but got " + data['VariantLabels']);
        }
        if (data['Products']) { // data not null
            // ensure the json data is an array
            if (!Array.isArray(data['Products'])) {
                throw new Error("Expected the field `Products` to be an array in the JSON data but got " + data['Products']);
            }
            // validate the optional field `Products` (array)
            for (const item of data['Products']) {
                ProductModelsWriteProduct.validateJsonObject(item);
            };
        }

        return true;
    }


}



/**
 * The optional internal name of the variant group.
 * @member {String} Name
 */
VariantModelsWriteVariantGroup.prototype['Name'] = undefined;

/**
 * A setting to control the display behaviour in product listings of variants belonging to this group.
 * @member {Boolean} CollapseInLists
 */
VariantModelsWriteVariantGroup.prototype['CollapseInLists'] = undefined;

/**
 * The labels of the variant data that this group keeps track of
 * @member {Array.<String>} VariantLabels
 */
VariantModelsWriteVariantGroup.prototype['VariantLabels'] = undefined;

/**
 * Products to be created and connected to the group.
 * @member {Array.<module:model/ProductModelsWriteProduct>} Products
 */
VariantModelsWriteVariantGroup.prototype['Products'] = undefined;






export default VariantModelsWriteVariantGroup;

