/**
 * geins-management-api-sdk-js
 *  Geins Management API is an RESTful api to power your applications who manages your geins services. Geins provides an easy-to-use and scalable solution for managing all aspects of an online store, from product listings and customer information to order processing and payment transactions.   :::tip With this API, you can build custom applications and integrate with third-party systems, dashboards and other bussiness logic apps. :::    ## Getting started Once you have created an account, you can start using the Management API by creating an `API key`. You can create as many API keys as you need. Each `API key` is connected to a specific account so you can keep track of operations and manage keys. You can find your `API key` in the `geins merchant center`.   ### Fast track Use one of our [SDKs](https://docs.geins.io/docs/sdk/introduction) to get started quickly. The SDKs are available for the most popular programming languages and frameworks.  Or, if you prefer to just take it for a test run:  [![Run in Postman](https://run.pstmn.io/button.svg)](https://god.gw.postman.com/run-collection/25895885-aaf6598f-1a7c-4949-85d7-ba846c42d553?action=collection%2Ffork&collection-url=entityId%3D25895885-aaf6598f-1a7c-4949-85d7-ba846c42d553%26entityType%3Dcollection%26workspaceId%3Da2a179ce-158e-46b0-8d06-e9640f45112c)  ### Authentication Two authentication methods are supported:   - `API Key`   - `Basic Auth` 
 *
 * The version of the OpenAPI document: v1.7.1
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 *
 */

import ApiClient from '../ApiClient';

/**
 * The WidgetRestrictionSetupWidgetRestrictionConfiguration model module.
 * @module model/WidgetRestrictionSetupWidgetRestrictionConfiguration
 * @version v1.7.1
 */
class WidgetRestrictionSetupWidgetRestrictionConfiguration {
    /**
     * Constructs a new <code>WidgetRestrictionSetupWidgetRestrictionConfiguration</code>.
     * @alias module:model/WidgetRestrictionSetupWidgetRestrictionConfiguration
     */
    constructor() { 
        
        WidgetRestrictionSetupWidgetRestrictionConfiguration.initialize(this);
    }

    /**
     * Initializes the fields of this object.
     * This method is used by the constructors of any subclasses, in order to implement multiple inheritance (mix-ins).
     * Only for internal use.
     */
    static initialize(obj) { 
    }

    /**
     * Constructs a <code>WidgetRestrictionSetupWidgetRestrictionConfiguration</code> from a plain JavaScript object, optionally creating a new instance.
     * Copies all relevant properties from <code>data</code> to <code>obj</code> if supplied or a new instance if not.
     * @param {Object} data The plain JavaScript object bearing properties of interest.
     * @param {module:model/WidgetRestrictionSetupWidgetRestrictionConfiguration} obj Optional instance to populate.
     * @return {module:model/WidgetRestrictionSetupWidgetRestrictionConfiguration} The populated <code>WidgetRestrictionSetupWidgetRestrictionConfiguration</code> instance.
     */
    static constructFromObject(data, obj) {
        if (data) {
            obj = obj || new WidgetRestrictionSetupWidgetRestrictionConfiguration();

            if (data.hasOwnProperty('ForcedResponsiveMode')) {
                obj['ForcedResponsiveMode'] = ApiClient.convertToType(data['ForcedResponsiveMode'], 'Number');
            }
            if (data.hasOwnProperty('AllowedSizes')) {
                obj['AllowedSizes'] = ApiClient.convertToType(data['AllowedSizes'], ['Number']);
            }
        }
        return obj;
    }

    /**
     * Validates the JSON data with respect to <code>WidgetRestrictionSetupWidgetRestrictionConfiguration</code>.
     * @param {Object} data The plain JavaScript object bearing properties of interest.
     * @return {boolean} to indicate whether the JSON data is valid with respect to <code>WidgetRestrictionSetupWidgetRestrictionConfiguration</code>.
     */
    static validateJSON(data) {
        // ensure the json data is an array
        if (!Array.isArray(data['AllowedSizes'])) {
            throw new Error("Expected the field `AllowedSizes` to be an array in the JSON data but got " + data['AllowedSizes']);
        }

        return true;
    }


}



/**
 * @member {module:model/WidgetRestrictionSetupWidgetRestrictionConfiguration.ForcedResponsiveModeEnum} ForcedResponsiveMode
 */
WidgetRestrictionSetupWidgetRestrictionConfiguration.prototype['ForcedResponsiveMode'] = undefined;

/**
 * @member {Array.<module:model/WidgetRestrictionSetupWidgetRestrictionConfiguration.AllowedSizesEnum>} AllowedSizes
 */
WidgetRestrictionSetupWidgetRestrictionConfiguration.prototype['AllowedSizes'] = undefined;





/**
 * Allowed values for the <code>ForcedResponsiveMode</code> property.
 * @enum {Number}
 * @readonly
 */
WidgetRestrictionSetupWidgetRestrictionConfiguration['ForcedResponsiveModeEnum'] = {

    /**
     * value: 0
     * @const
     */
    "0": 0,

    /**
     * value: 1
     * @const
     */
    "1": 1
};


/**
 * Allowed values for the <code>allowedSizes</code> property.
 * @enum {Number}
 * @readonly
 */
WidgetRestrictionSetupWidgetRestrictionConfiguration['AllowedSizesEnum'] = {

    /**
     * value: 1
     * @const
     */
    "1": 1,

    /**
     * value: 2
     * @const
     */
    "2": 2,

    /**
     * value: 3
     * @const
     */
    "3": 3,

    /**
     * value: 4
     * @const
     */
    "4": 4,

    /**
     * value: 5
     * @const
     */
    "5": 5,

    /**
     * value: 6
     * @const
     */
    "6": 6
};



export default WidgetRestrictionSetupWidgetRestrictionConfiguration;

