/**
 * geins-management-api-sdk-js
 *  Geins Management API is an RESTful api to power your applications who manages your geins services. Geins provides an easy-to-use and scalable solution for managing all aspects of an online store, from product listings and customer information to order processing and payment transactions.   :::tip With this API, you can build custom applications and integrate with third-party systems, dashboards and other bussiness logic apps. :::    ## Getting started Once you have created an account, you can start using the Management API by creating an `API key`. You can create as many API keys as you need. Each `API key` is connected to a specific account so you can keep track of operations and manage keys. You can find your `API key` in the `geins merchant center`.   ### Fast track Use one of our [SDKs](https://docs.geins.io/docs/sdk/introduction) to get started quickly. The SDKs are available for the most popular programming languages and frameworks.  Or, if you prefer to just take it for a test run:  [![Run in Postman](https://run.pstmn.io/button.svg)](https://god.gw.postman.com/run-collection/25895885-aaf6598f-1a7c-4949-85d7-ba846c42d553?action=collection%2Ffork&collection-url=entityId%3D25895885-aaf6598f-1a7c-4949-85d7-ba846c42d553%26entityType%3Dcollection%26workspaceId%3Da2a179ce-158e-46b0-8d06-e9640f45112c)  ### Authentication Two authentication methods are supported:   - `API Key`   - `Basic Auth` 
 *
 * The version of the OpenAPI document: v1.7.1
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 *
 */


import ApiClient from "../ApiClient";
import EnvelopePageAreaModelsReadPageArea from '../model/EnvelopePageAreaModelsReadPageArea';
import EnvelopePageAreaModelsReadPageAreaFamily from '../model/EnvelopePageAreaModelsReadPageAreaFamily';
import PageAreaModelsReadPageArea from '../model/PageAreaModelsReadPageArea';
import PageAreaModelsReadPageAreaFamily from '../model/PageAreaModelsReadPageAreaFamily';
import PageAreaModelsWritePageArea from '../model/PageAreaModelsWritePageArea';
import PageAreaModelsWritePageAreaFamily from '../model/PageAreaModelsWritePageAreaFamily';

/**
* PageArea service.
* @module api/PageAreaApi
* @version v1.7.1
*/
export default class PageAreaApi {

    /**
    * Constructs a new PageAreaApi. 
    * @alias module:api/PageAreaApi
    * @class
    * @param {module:ApiClient} [apiClient] Optional API client implementation to use,
    * default to {@link module:ApiClient#instance} if unspecified.
    */
    constructor(apiClient) {
        this.apiClient = apiClient || ApiClient.instance;
    }


    /**
     * Callback function to receive the result of the createOrUpdateAPageArea operation.
     * @callback module:api/PageAreaApi~createOrUpdateAPageAreaCallback
     * @param {String} error Error message, if any.
     * @param {module:model/EnvelopePageAreaModelsReadPageArea} data The data returned by the service call.
     * @param {String} response The complete HTTP response.
     */

    /**
     * Create or update a page area
     * @param {module:model/PageAreaModelsWritePageArea} area The area model to create or update.
     * @param {module:api/PageAreaApi~createOrUpdateAPageAreaCallback} callback The callback function, accepting three arguments: error, data, response
     * data is of type: {@link module:model/EnvelopePageAreaModelsReadPageArea}
     */
    createOrUpdateAPageArea(area, callback) {
      let postBody = area;
      // verify the required parameter 'area' is set
      if (area === undefined || area === null) {
        throw new Error("Missing the required parameter 'area' when calling createOrUpdateAPageArea");
      }

      let pathParams = {
      };
      let queryParams = {
      };
      let headerParams = {
      };
      let formParams = {
      };

      let authNames = ['apiKey', 'basicAuth'];
      let contentTypes = ['application/json', 'text/json', 'application/xml', 'text/xml', 'application/x-www-form-urlencoded'];
      let accepts = ['application/json', 'text/json', 'application/xml', 'text/xml'];
      let returnType = EnvelopePageAreaModelsReadPageArea;
      return this.apiClient.callApi(
        '/API/PageArea', 'POST',
        pathParams, queryParams, headerParams, formParams, postBody,
        authNames, contentTypes, accepts, returnType, null, callback
      );
    }

    /**
     * Callback function to receive the result of the createOrUpdatePageAreaFamily operation.
     * @callback module:api/PageAreaApi~createOrUpdatePageAreaFamilyCallback
     * @param {String} error Error message, if any.
     * @param {module:model/EnvelopePageAreaModelsReadPageAreaFamily} data The data returned by the service call.
     * @param {String} response The complete HTTP response.
     */

    /**
     * Create or update a page area family
     * @param {module:model/PageAreaModelsWritePageAreaFamily} family The family model to create or update.
     * @param {module:api/PageAreaApi~createOrUpdatePageAreaFamilyCallback} callback The callback function, accepting three arguments: error, data, response
     * data is of type: {@link module:model/EnvelopePageAreaModelsReadPageAreaFamily}
     */
    createOrUpdatePageAreaFamily(family, callback) {
      let postBody = family;
      // verify the required parameter 'family' is set
      if (family === undefined || family === null) {
        throw new Error("Missing the required parameter 'family' when calling createOrUpdatePageAreaFamily");
      }

      let pathParams = {
      };
      let queryParams = {
      };
      let headerParams = {
      };
      let formParams = {
      };

      let authNames = ['apiKey', 'basicAuth'];
      let contentTypes = ['application/json', 'text/json', 'application/xml', 'text/xml', 'application/x-www-form-urlencoded'];
      let accepts = ['application/json', 'text/json', 'application/xml', 'text/xml'];
      let returnType = EnvelopePageAreaModelsReadPageAreaFamily;
      return this.apiClient.callApi(
        '/API/PageAreaFamily', 'POST',
        pathParams, queryParams, headerParams, formParams, postBody,
        authNames, contentTypes, accepts, returnType, null, callback
      );
    }

    /**
     * Callback function to receive the result of the getPageArea operation.
     * @callback module:api/PageAreaApi~getPageAreaCallback
     * @param {String} error Error message, if any.
     * @param {module:model/PageAreaModelsReadPageArea} data The data returned by the service call.
     * @param {String} response The complete HTTP response.
     */

    /**
     * Get a specific page area
     * @param {String} name The name of the page area to get.
     * @param {module:api/PageAreaApi~getPageAreaCallback} callback The callback function, accepting three arguments: error, data, response
     * data is of type: {@link module:model/PageAreaModelsReadPageArea}
     */
    getPageArea(name, callback) {
      let postBody = null;
      // verify the required parameter 'name' is set
      if (name === undefined || name === null) {
        throw new Error("Missing the required parameter 'name' when calling getPageArea");
      }

      let pathParams = {
        'name': name
      };
      let queryParams = {
      };
      let headerParams = {
      };
      let formParams = {
      };

      let authNames = ['apiKey', 'basicAuth'];
      let contentTypes = [];
      let accepts = ['application/json', 'text/json', 'application/xml', 'text/xml'];
      let returnType = PageAreaModelsReadPageArea;
      return this.apiClient.callApi(
        '/API/PageArea/{name}', 'GET',
        pathParams, queryParams, headerParams, formParams, postBody,
        authNames, contentTypes, accepts, returnType, null, callback
      );
    }

    /**
     * Callback function to receive the result of the getPageAreaFamily operation.
     * @callback module:api/PageAreaApi~getPageAreaFamilyCallback
     * @param {String} error Error message, if any.
     * @param {module:model/PageAreaModelsReadPageAreaFamily} data The data returned by the service call.
     * @param {String} response The complete HTTP response.
     */

    /**
     * Get a specific page area family
     * @param {Number} familyId The id of the page area family to get.
     * @param {module:api/PageAreaApi~getPageAreaFamilyCallback} callback The callback function, accepting three arguments: error, data, response
     * data is of type: {@link module:model/PageAreaModelsReadPageAreaFamily}
     */
    getPageAreaFamily(familyId, callback) {
      let postBody = null;
      // verify the required parameter 'familyId' is set
      if (familyId === undefined || familyId === null) {
        throw new Error("Missing the required parameter 'familyId' when calling getPageAreaFamily");
      }

      let pathParams = {
        'familyId': familyId
      };
      let queryParams = {
      };
      let headerParams = {
      };
      let formParams = {
      };

      let authNames = ['apiKey', 'basicAuth'];
      let contentTypes = [];
      let accepts = ['application/json', 'text/json', 'application/xml', 'text/xml'];
      let returnType = PageAreaModelsReadPageAreaFamily;
      return this.apiClient.callApi(
        '/API/PageAreaFamily/{familyId}', 'GET',
        pathParams, queryParams, headerParams, formParams, postBody,
        authNames, contentTypes, accepts, returnType, null, callback
      );
    }

    /**
     * Callback function to receive the result of the listPageAreaFamilies operation.
     * @callback module:api/PageAreaApi~listPageAreaFamiliesCallback
     * @param {String} error Error message, if any.
     * @param {Array.<module:model/PageAreaModelsReadPageAreaFamily>} data The data returned by the service call.
     * @param {String} response The complete HTTP response.
     */

    /**
     * Gets a list of all page area families, including nested data
     * @param {module:api/PageAreaApi~listPageAreaFamiliesCallback} callback The callback function, accepting three arguments: error, data, response
     * data is of type: {@link Array.<module:model/PageAreaModelsReadPageAreaFamily>}
     */
    listPageAreaFamilies(callback) {
      let postBody = null;

      let pathParams = {
      };
      let queryParams = {
      };
      let headerParams = {
      };
      let formParams = {
      };

      let authNames = ['apiKey', 'basicAuth'];
      let contentTypes = [];
      let accepts = ['application/json', 'text/json', 'application/xml', 'text/xml'];
      let returnType = [PageAreaModelsReadPageAreaFamily];
      return this.apiClient.callApi(
        '/API/PageAreaFamily/List', 'GET',
        pathParams, queryParams, headerParams, formParams, postBody,
        authNames, contentTypes, accepts, returnType, null, callback
      );
    }


}
